const state = { route: location.pathname === '/' ? '/chat' : location.pathname, conversations: [], conversationId: null, dashboard: null, keys: [], user: null };
const app = document.querySelector('#app');
const api = async (url, options) => { const response = await fetch(url, {...(options||{}), credentials: 'same-origin'}); let data = null; try { data = await response.json(); } catch(e) { data = null; } if (!response.ok) { const detail = data && (typeof data.message === 'string' ? data.message : (typeof data.error === 'string' ? data.error : data.error && data.error.message)); throw new Error(detail || ('请求未完成（HTTP ' + response.status + '）')); } return data; };
const escapeHtml = (text) => String(text).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const logo = '<img src="/assets/stardevil-mark.png" alt="星魔 Logo">';
const chatLogo = '<img src="/assets/stardevil-mark.png" alt="星魔 Logo">';
const menuIcon = '<svg class="menu-icon" viewBox="0 0 20 20" width="16" height="16" aria-hidden="true" focusable="false"><rect x="2" y="4.4" width="16" height="1.7" rx="0.85" fill="currentColor"></rect><rect x="2" y="9.15" width="16" height="1.7" rx="0.85" fill="currentColor"></rect><rect x="2" y="13.9" width="16" height="1.7" rx="0.85" fill="currentColor"></rect></svg>';
const isMobile = () => window.matchMedia('(max-width:760px)').matches;
function setSidebar(open) { const shell = document.querySelector('.chat-shell'); if (shell) shell.classList.toggle('sidebar-open', !!open); }
function closeSidebar() { setSidebar(false); }

function nav() { return `<header class="topbar"><a class="brand" href="/chat" data-route>${logo}<span>星魔<small>STARDEVIL</small></span></a><nav class="nav"><button data-route="/chat" class="${state.route==='/chat'?'active':''}">智能对话</button><button data-route="/admin" class="${state.route==='/admin'?'active':''}">控制台</button><button data-route="/developer" class="${state.route==='/developer'?'active':''}">开发者</button></nav><div class="top-actions"><span class="status">服务正常</span><span class="user-name">${state.user?state.user.username:''}</span><button data-action="logout" class="top-logout">退出</button><span class="avatar">${state.user&&state.user.username?state.user.username[0].toUpperCase():'Y'}</span></div></header>`; }
function shell(body) { app.innerHTML = `<main class="shell">${nav()}${body}</main>`; bindRoutes(); }
function bindRoutes() { document.querySelectorAll('[data-route]').forEach(item => item.addEventListener('click', event => { event.preventDefault(); navigate(item.dataset.route || item.getAttribute('href')); })); }
function navigate(path) { history.pushState({}, '', path); state.route=path; render(); }
window.addEventListener('popstate', () => { state.route=location.pathname; render(); });

async function renderChat() {
  await loadConversations();
  app.innerHTML = `<main class="chat-shell">
    <aside class="doubao-sidebar">
      <a class="chat-brand" href="/chat" data-route>${chatLogo}<span><b>星魔</b></span></a>
      <button id="newChat" class="side-new"><b>+</b><span>新建对话</span></button>
      <nav class="side-actions">
        <button class="side-action active"><i>◌</i><span>智能对话</span></button>
        <button class="side-action" data-route="/admin"><i>□</i><span>控制台</span></button>
        <button class="side-action" data-route="/developer"><i>⌘</i><span>API 服务</span></button>
      </nav>
      <div class="history-head"><span>最近对话</span><small>${state.conversations.length}</small></div>
      <div id="conversationList" class="history-list">${conversationList()}</div>
      <div class="sidebar-foot"><span class="foot-avatar">${state.user&&state.user.username?state.user.username[0].toUpperCase():'Y'}</span><span><b>${state.user?state.user.username:'Ynchen'}</b><small>星魔演示空间</small></span><button title="控制台" data-route="/admin">...</button><button title="退出登录" data-action="logout">⎋</button></div>
    </aside>
    <div class="sidebar-scrim" data-action="close-sidebar" aria-hidden="true"></div>
    <section class="doubao-main">
      <header class="chat-topline"><button class="collapse-button" data-action="toggle-sidebar" aria-label="打开侧边栏" title="侧边栏">${menuIcon}</button><div class="chat-top-actions"><button title="模型状态">服务正常</button><button title="更多操作">...</button></div></header>
      <section class="doubao-stage">
        <div id="chatScroll" class="doubao-scroll"><div id="chatContent">${state.conversationId ? '<div class="message-list"></div>' : welcome()}</div></div>
        <div class="doubao-composer-wrap"><div class="doubao-composer">
          <textarea id="prompt" placeholder="发消息给星魔" aria-label="输入问题"></textarea>
          <div class="composer-tools"><div><button class="tool-plus" title="添加内容">+</button><button class="composer-tool">智能对话</button><button class="composer-tool">企业知识</button></div><button id="send" class="doubao-send" disabled title="发送消息">↑</button></div>
        </div><p class="composer-note">星魔可能会生成不准确信息，请以实际业务资料为准</p></div>
      </section>
    </section>
  </main>`;
  bindRoutes();
  document.querySelector('#newChat').addEventListener('click', newChat);
  document.querySelector('#send').addEventListener('click', sendMessage);
  const prompt = document.querySelector('#prompt');
  prompt.addEventListener('input', () => document.querySelector('#send').disabled = !prompt.value.trim());
  prompt.addEventListener('keydown', event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); sendMessage(); } });
  document.querySelectorAll('[data-conversation]').forEach(button => button.addEventListener('click', () => openConversation(button.dataset.conversation)));
  if (state.conversationId) await openConversation(state.conversationId, false);
}
function welcome(){return `<div class="doubao-welcome"><div class="welcome-brand"><div class="welcome-mark">${chatLogo}</div><small>STARDEVIL</small></div><h1>有什么我能帮你的吗？</h1><p>星魔企业智能助手，为业务咨询、资料问答和智能服务提供支持。</p><div class="mode-switch"><button class="selected">对话</button><button>工作</button></div><div class="recommend-label">为你推荐</div><div class="recommend-list"><button data-prompt="介绍一下星魔可以为企业提供哪些能力">介绍一下星魔可以为企业提供哪些能力</button><button data-prompt="如何通过 API 接入星魔的智能对话能力">如何通过 API 接入星魔的智能对话能力</button><button data-prompt="帮我整理一个智能客服的落地方案">帮我整理一个智能客服的落地方案</button><button data-prompt="根据企业资料生成一份客户服务介绍">根据企业资料生成一份客户服务介绍</button></div></div>`;}
function conversationList(){return state.conversations.length?state.conversations.map(item=>`<button class="conversation ${item.id===state.conversationId?'active':''}" data-conversation="${item.id}" title="${escapeHtml(item.title)}"><i>◌</i><span>${escapeHtml(item.title)}</span></button>`).join(''):'<p class="empty-history">暂时没有对话</p>';}
async function loadConversations(){state.conversations=await api('/api/conversations');}
async function newChat(){state.conversationId=null; await renderChat();}
async function openConversation(id, refresh=true){state.conversationId=id;if(refresh)return renderChat();closeSidebar();const messages=await api(`/api/conversations/${id}`);const list=document.querySelector('.message-list');if(!list)return;list.innerHTML=messages.map(message=>messageHtml(message.role,message.content,message.sources)).join('');document.querySelector('#chatScroll').scrollTop=999999;}
function messageHtml(role, content, sources=[]){return `<article class="message ${role==='assistant'?'ai':'user'}"><div class="badge">${role==='assistant'?'M':'Y'}</div><div class="message-content"><div class="bubble">${escapeHtml(content)}</div>${role==='assistant'&&sources.length?sourceHtml(sources):''}</div></article>`;}
function sourceHtml(sources){return `<div class="source-list"><span>参考资料</span>${sources.map(source=>`<b>${escapeHtml(source.name)}</b>`).join('')}</div>`;}
async function sendMessage(){
  const input=document.querySelector('#prompt'); const message=input.value.trim(); if(!message)return;
  input.value=''; document.querySelector('#send').disabled=true;
  let list=document.querySelector('.message-list');
  if(!list){document.querySelector('#chatContent').innerHTML='<div class="message-list"></div>';list=document.querySelector('.message-list');}
  list.insertAdjacentHTML('beforeend',messageHtml('user',message));
  list.insertAdjacentHTML('beforeend','<article class="message ai" id="assistantPending"><div class="badge">M</div><div class="message-content"><div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div></div></article>');
  document.querySelector('#chatScroll').scrollTop=999999;
  try {
    const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:state.conversationId,message})});
    if(!response.ok) throw new Error('对话服务暂不可用');
    state.conversationId=response.headers.get('X-Conversation-Id')||state.conversationId;
    const reader=response.body.getReader(); const decoder=new TextDecoder(); let buffer='',answer='',sources=[]; const target=document.querySelector('#assistantPending .bubble');
    while(true){
      const {value,done}=await reader.read(); if(done)break; buffer+=decoder.decode(value,{stream:true}); const events=buffer.split('\n\n'); buffer=events.pop();
      events.forEach(event=>{const dataLine=event.split('\n').find(line=>line.startsWith('data: '));if(!dataLine)return;try{const data=JSON.parse(dataLine.slice(6));if(data.delta){answer+=data.delta;target.textContent=answer;document.querySelector('#chatScroll').scrollTop=999999;}if(data.sources){sources=data.sources;}}catch{}});
    }
    if(sources.length) document.querySelector('#assistantPending .message-content')?.insertAdjacentHTML('beforeend',sourceHtml(sources));
  } catch (error) { document.querySelector('#assistantPending .bubble').textContent=error.message||'对话服务暂不可用'; }
  document.querySelector('#assistantPending')?.removeAttribute('id'); await loadConversations(); document.querySelector('#conversationList').innerHTML=conversationList(); document.querySelectorAll('[data-conversation]').forEach(button=>button.addEventListener('click',()=>openConversation(button.dataset.conversation)));
}

function consoleNav(active){return `<aside class="console-nav"><div class="nav-heading">星魔控制台</div><button class="${active==='dashboard'?'active':''}" data-console="dashboard">概览</button><button class="${active==='knowledge'?'active':''}" data-console="knowledge">企业知识库</button><button class="${active==='keys'?'active':''}" data-console="keys">API 密钥</button><button class="${active==='conversations'?'active':''}" data-console="conversations">对话记录</button><button class="${active==='settings'?'active':''}" data-console="settings">模型通道</button></aside>`;}
function bindConsole(){document.querySelectorAll('[data-console]').forEach(button=>button.addEventListener('click',()=>renderAdmin(button.dataset.console)));}
async function renderAdmin(section='dashboard'){const content=section==='dashboard'?await dashboardView():section==='knowledge'?await knowledgeView():section==='keys'?await keysView():section==='conversations'?await conversationsView():await settingsView();shell(`<section class="console">${consoleNav(section)}<section class="console-content">${content}</section></section>`);bindConsole();if(section==='knowledge')bindKnowledge();if(section==='keys')bindKeyForm();if(section==='settings')bindSettingsForm();}
async function dashboardView(){const data=await api('/api/dashboard');return `<div class="page-heading"><div><h1>运营概览</h1><p>星魔服务运行稳定，当前展示数据来自本地演示环境。</p></div><button class="button primary" data-console="keys">创建 API Key</button></div><section class="metrics">${data.metrics.map(metric=>`<article class="metric"><div class="metric-label">${metric.label}</div><div class="metric-value">${metric.value}</div><div class="metric-delta ${metric.tone}">${metric.delta}</div></article>`).join('')}</section><section class="data-grid"><article class="panel"><div class="panel-head"><h2>近 7 日请求趋势</h2><span class="tag">网关正常</span></div><div class="panel-body"><div class="chart">${[42,65,48,78,70,91,84,98,75,59,83,68,94,88].map((n,i)=>`<span class="bar ${i>10?'highlight':''}" style="height:${n}%"></span>`).join('')}</div></div></article><article class="panel"><div class="panel-head"><h2>运行动态</h2><span style="color:#90969e;font-size:12px">实时</span></div><div class="panel-body"><div class="activity">${data.activity.map(item=>`<div class="activity-item"><i class="activity-dot ${item.status==='info'?'info':''}"></i><span>${item.text}</span><time>${item.time}</time></div>`).join('')}</div></div></article></section><section class="data-grid"><article class="panel"><div class="panel-head"><h2>对外 API</h2><button class="button small" data-route="/developer">查看文档</button></div><div class="panel-body"><div class="endpoint"><b class="method">POST</b><code>http://127.0.0.1:5178/v1/chat/completions</code></div><div class="info-list"><div><strong>公开模型名称</strong><span>xingmo-chat · 对外统一模型别名</span></div><div><strong>网关状态</strong><span>演示模式。生产环境接入 NewAPI 后不改变前端调用方式。</span></div></div></div></article><article class="panel"><div class="panel-head"><h2>交付边界</h2></div><div class="panel-body"><div class="info-list"><div><strong>对外展示</strong><span>星魔前台、星魔后台、星魔 API 文档</span></div><div><strong>内部基础设施</strong><span>NewAPI、模型通道、物理机推理服务</span></div></div></div></article></section>`;}
async function keysView(){state.keys=await api('/api/keys');return `<div class="page-heading"><div><h1>API 密钥</h1><p>创建给合作方使用的星魔访问凭证，并设置每日演示额度。</p></div><button id="createKey" class="button primary">创建密钥</button></div><article class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>名称</th><th>访问密钥</th><th>每日额度</th><th>今日用量</th><th>状态</th><th>创建时间</th></tr></thead><tbody>${state.keys.map(key=>`<tr><td>${escapeHtml(key.name)}</td><td><code>${key.token_prefix}</code></td><td>${Number(key.daily_limit).toLocaleString()} Token</td><td>${Number(key.used_today).toLocaleString()} Token</td><td><span class="tag ${key.enabled?'':'gray'}">${key.enabled?'已启用':'已禁用'}</span></td><td>${key.created_at}</td></tr>`).join('')}</tbody></table></div></article>`;}
function bindKeyForm(){document.querySelector('#createKey').addEventListener('click',async()=>{const name=prompt('请输入密钥名称','演示合作方 Key');if(name===null)return;const response=await api('/api/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,daily_limit:10000})});toast(`密钥已创建：${response.token}（仅本次展示）`);renderAdmin('keys');});}
async function conversationsView(){const rows=await api('/api/conversations');return `<div class="page-heading"><div><h1>对话记录</h1><p>星魔对外聊天页面产生的会话会保存在本地演示数据库中。</p></div><button class="button" data-route="/chat">打开聊天页</button></div><article class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>会话主题</th><th>创建时间</th><th>最近更新</th><th>操作</th></tr></thead><tbody>${rows.length?rows.map(row=>`<tr><td>${escapeHtml(row.title)}</td><td>${row.created_at}</td><td>${row.updated_at}</td><td><button class="button small" data-open-chat="${row.id}">查看</button></td></tr>`).join(''):'<tr><td colspan="4" style="text-align:center;color:#8c9299">尚无对话记录</td></tr>'}</tbody></table></div></article>`;}
async function knowledgeView(){const documents=await api('/api/knowledge/documents');return `<div class="page-heading"><div><h1>企业知识库</h1><p>导入公司资料后，星魔会在回答前检索相关内容，并将命中的资料作为上下文参考。</p></div><span class="tag">本地检索已启用</span></div><section class="knowledge-grid"><article class="panel"><div class="panel-head"><h2>导入资料</h2><span class="knowledge-hint">文本型资料</span></div><div class="panel-body"><div class="field"><label>资料名称</label><input id="knowledgeName" placeholder="例如：星魔产品介绍"></div><div class="field"><label>选择文件</label><input id="knowledgeFile" type="file" accept=".txt,.md,.csv,.json,.html"></div><div class="field"><label>资料正文</label><textarea id="knowledgeContent" class="knowledge-textarea" placeholder="粘贴公司介绍、产品手册、FAQ、案例或制度内容。也可以先选择 TXT、MD、CSV、JSON、HTML 文件。"></textarea></div><button id="importKnowledge" class="button dark">导入知识库</button><p class="knowledge-note">当前版本支持本地文本切块与检索；PDF、Word、Excel 解析和向量 Embedding 会在下一阶段接入。</p></div></article><article class="panel"><div class="panel-head"><h2>检索测试</h2><span class="knowledge-hint">回答前检索</span></div><div class="panel-body"><div class="field"><label>测试问题</label><input id="knowledgeQuery" placeholder="例如：星魔可以提供哪些服务？"></div><button id="searchKnowledge" class="button">开始检索</button><div id="knowledgeResults" class="knowledge-results"><p>导入资料后，可在这里验证资料是否能被命中。</p></div></div></article></section><article class="panel knowledge-documents"><div class="panel-head"><h2>已导入资料</h2><span>${documents.length} 份</span></div><div class="table-wrap"><table class="table"><thead><tr><th>资料名称</th><th>来源</th><th>切块数量</th><th>导入时间</th><th></th></tr></thead><tbody>${documents.length?documents.map(doc=>`<tr><td>${escapeHtml(doc.name)}</td><td>${escapeHtml(doc.source_type)}</td><td>${doc.chunk_count}</td><td>${doc.created_at}</td><td><button class="button small" data-document-delete="${doc.id}">删除</button></td></tr>`).join(''):'<tr><td colspan="5" style="text-align:center;color:#8c9299">暂未导入资料</td></tr>'}</tbody></table></div></article>`;}
function bindKnowledge(){
  const file=document.querySelector('#knowledgeFile'); const name=document.querySelector('#knowledgeName'); const content=document.querySelector('#knowledgeContent');
  file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;if(!name.value)name.value=selected.name.replace(/\.[^.]+$/,'');const reader=new FileReader();reader.onload=()=>{content.value=String(reader.result||'');};reader.readAsText(selected,'utf-8');});
  document.querySelector('#importKnowledge').addEventListener('click',async()=>{try{const item=await api('/api/knowledge/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.value,content:content.value,source_type:file.files?.[0]?.name.split('.').pop()||'text'})});toast(`已导入《${item.name}》，生成 ${item.chunk_count} 个知识片段`);renderAdmin('knowledge');}catch(error){toast(error.message||'资料导入失败');}});
  document.querySelector('#searchKnowledge').addEventListener('click',async()=>{const query=document.querySelector('#knowledgeQuery').value.trim();if(!query)return toast('请输入测试问题');try{const results=await api('/api/knowledge/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const target=document.querySelector('#knowledgeResults');target.innerHTML=results.length?results.map(item=>`<article><b>${escapeHtml(item.name)}</b><p>${escapeHtml(item.excerpt)}</p></article>`).join(''):'<p>没有命中相关资料，请补充资料正文或换一个问题。</p>';}catch(error){toast(error.message||'检索失败');}});
  document.querySelectorAll('[data-document-delete]').forEach(button=>button.addEventListener('click',async()=>{await api(`/api/knowledge/documents/${button.dataset.documentDelete}`,{method:'DELETE'});toast('资料已删除');renderAdmin('knowledge');}));
}
async function settingsView(){const settings=await api('/api/settings');const isCustom=['custom','newapi'].includes(settings.upstream_mode);return `<div class="page-heading"><div><h1>模型通道配置</h1><p>选择协议并填写模型服务的 Base URL、API Key 和模型名称。保存后，星魔聊天与对外 API 会统一使用该通道。</p></div><span class="tag ${isCustom?'':'gray'}">当前：${isCustom?'自定义通道':'演示模式'}${isCustom?(settings.channel_source==='global'?'（继承全局默认通道）':'（本账号配置）'):''}</span></div><section class="setting-grid"><article class="panel"><div class="panel-head"><h2>内部模型通道</h2><span class="knowledge-hint">密钥仅保存在服务端</span></div><div class="panel-body"><div class="field"><label>运行模式</label><select id="upstreamMode"><option value="demo" ${isCustom?'':'selected'}>演示模式（本地模拟回复）</option><option value="custom" ${isCustom?'selected':''}>自定义模型通道</option></select></div><div class="field"><label>上游协议</label><select id="upstreamProtocol"><option value="openai" ${settings.upstream_protocol==='anthropic'?'':'selected'}>OpenAI Chat Completions 兼容</option><option value="anthropic" ${settings.upstream_protocol==='anthropic'?'selected':''}>Anthropic Messages 兼容</option></select></div><div class="field"><label>Base URL</label><input id="upstreamBase" value="${escapeHtml(settings.upstream_base_url||'')}" placeholder="例如 https://api.example.com/v1"></div><div class="field"><label>API Key</label><input id="upstreamKey" type="password" value="" placeholder="${settings.has_api_key?'已保存；留空则不修改':'填写模型服务的 API Key'}"></div><div class="field"><label>模型名称</label><input id="upstreamModel" value="${escapeHtml(settings.upstream_model||'')}" placeholder="例如 gpt-4o-mini / claude-sonnet"></div><div class="field" style="margin-top:6px"><label style="display:flex;gap:8px;align-items:center;cursor:pointer"><input type="checkbox" id="exposeModels" ${settings.expose_real_models?'checked':''} style="width:auto;height:auto;margin:0"> 对外 /v1/models 暴露真实模型名（关闭则仅返回 xingmo-chat）</label></div><p class="knowledge-note">测试按钮使用上方表单的当前内容（API Key 留空则沿用已保存的那把）；保存后才对聊天与对外 API 生效。</p><div class="field"><button id="fetchModels" type="button" class="button">测试连接并列出模型</button></div><div id="modelFetchResult" class="knowledge-results"><p>点击“测试连接并列出模型”，从已配置的上游通道真实拉取模型列表（演示模式或未配置上游时不可用）。</p></div><button id="saveSettings" class="button dark">保存并启用</button><p class="knowledge-note">OpenAI 协议会调用 <code>/v1/chat/completions</code>；Anthropic 协议会调用 <code>/v1/messages</code>。如供应商已在 Base URL 中包含路径，系统会自动识别。</p></div></article><article class="panel"><div class="panel-head"><h2>对外契约</h2></div><div class="panel-body"><div class="field"><label>对外 API 地址</label><input value="http://127.0.0.1:5178/v1" readonly></div><div class="field"><label>对外模型名称</label><input value="xingmo-chat" readonly></div><div class="notice">无论内部使用哪家模型服务，访客和合作方始终调用星魔地址与 <strong>xingmo-chat</strong>。系统不会将真实 Base URL、API Key 或上游模型名返回给浏览器和下游。</div></div></article></section>`;}
function bindSettingsForm(){document.querySelector('#saveSettings').addEventListener('click',async()=>{try{const response=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({upstream_base_url:document.querySelector('#upstreamBase').value,upstream_api_key:document.querySelector('#upstreamKey').value,upstream_model:document.querySelector('#upstreamModel').value,upstream_protocol:document.querySelector('#upstreamProtocol').value,upstream_mode:document.querySelector('#upstreamMode').value,expose_real_models:document.querySelector('#exposeModels')?document.querySelector('#exposeModels').checked:false})});toast(response.upstream_mode==='custom'?'模型通道已保存并启用':'已切换为本地演示模式');renderAdmin('settings');}catch(error){toast(error.message||'保存配置失败');}});const fetchBtn=document.querySelector('#fetchModels');if(fetchBtn){fetchBtn.addEventListener('click',async()=>{const target=document.querySelector('#modelFetchResult');if(!target)return;target.innerHTML='<p>正在从上游拉取模型列表…</p>';try{const res=await api('/api/models/fetch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({upstream_mode:document.querySelector('#upstreamMode').value,upstream_protocol:document.querySelector('#upstreamProtocol').value,upstream_base_url:document.querySelector('#upstreamBase').value,upstream_api_key:document.querySelector('#upstreamKey').value,upstream_model:document.querySelector('#upstreamModel').value})});if(res.ok&&res.models){target.innerHTML=res.models.length?res.models.map(m=>`<article><b>${escapeHtml(m)}</b></article>`).join(''):'<p>上游未返回模型。</p>';}else{target.innerHTML=`<p>${escapeHtml(res.message||'拉取失败')}</p>`;}}catch(e){target.innerHTML=`<p>${escapeHtml(e.message||'拉取失败，请检查网络或上游配置。')}</p>`;}});}}
async function renderDeveloper(){shell(`<section class="console"><aside class="console-nav"><div class="nav-heading">开发者中心</div><button class="active">API 接入</button><button>调用示例</button><button>错误码</button></aside><section class="console-content"><div class="page-heading"><div><h1>星魔 API</h1><p>OpenAI 兼容接口。合作方只需要替换 Base URL、API Key 和模型名称即可接入。</p></div><span class="tag">兼容 OpenAI</span></div><section class="api-layout"><div><article class="panel"><div class="panel-head"><h2>创建对话补全</h2><span class="method">POST</span></div><div class="endpoint"><b class="method">POST</b><code>/v1/chat/completions</code></div><pre class="code">curl <b>http://127.0.0.1:5178/v1/chat/completions</b> \\
  -H <em>"Authorization: Bearer YOUR_XINGMO_KEY"</em> \\
  -H <em>"Content-Type: application/json"</em> \\
  -d '{
    "model": <em>"xingmo-chat"</em>,
    "stream": true,
    "messages": [{"role":"user","content":"你好，介绍一下星魔"}]
  }'</pre></article><article class="panel" style="margin-top:16px"><div class="panel-head"><h2>接口约定</h2></div><div class="panel-body"><div class="info-list"><div><strong>认证</strong><span>在 Authorization Header 中使用 Bearer Token。</span></div><div><strong>模型别名</strong><span>始终传入 xingmo-chat。该别名会在服务端映射到内部模型通道。</span></div><div><strong>流式输出</strong><span>设置 stream=true 后以 SSE 返回，响应中的 model 字段保持为 xingmo-chat。</span></div></div></div></article></div><aside class="panel"><div class="panel-head"><h2>接入信息</h2></div><div class="panel-body"><div class="info-list"><div><strong>Base URL</strong><span>http://127.0.0.1:5178/v1</span></div><div><strong>默认模型</strong><span>xingmo-chat</span></div><div><strong>协议</strong><span>OpenAI Chat Completions</span></div><div><strong>安全边界</strong><span>不返回内部 NewAPI、真实模型或物理机服务地址。</span></div></div></div></aside></section></section></section>`);}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),4000);}
async function render(){
  try { const res = await fetch('/api/auth/me', {credentials:'same-origin'}); const data = await res.json(); state.user = data.user || null; }
  catch(e){ state.user = null; }
  if(!state.user){ state.route='/login'; return renderLogin(); }
  if(state.route==='/login'||state.route==='/') state.route='/chat';
  if(state.route==='/chat')return renderChat();
  if(state.route==='/admin')return renderAdmin();
  if(state.route==='/developer')return renderDeveloper();
  return renderChat();
}
async function doLogout(){ try{ await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'}); }catch(e){} state.user=null; state.route='/login'; render(); }
async function renderLogin(){
  app.innerHTML = `<main class="auth-shell"><div class="auth-card"><div class="auth-brand">${logo}<span>星魔<small>STARDEVIL</small></span></div><h1>登录星魔控制台</h1><div class="auth-tabs"><button data-tab="login" class="active">登录</button><button data-tab="register">注册</button></div><form id="authForm" class="auth-form"><div class="field"><label>用户名</label><input id="authUser" placeholder="请输入用户名" autocomplete="username"></div><div class="field"><label>密码</label><input id="authPass" type="password" placeholder="请输入密码" autocomplete="current-password"></div><button id="authSubmit" class="button dark" type="submit" style="margin-top:6px">登录</button></form><p class="auth-hint">试用账号：admin / admin123（注册的新账号将拥有独立的模型通道配置）</p></div></main>`;
  let mode='login';
  document.querySelectorAll('.auth-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.auth-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.tab;document.querySelector('#authSubmit').textContent=mode==='login'?'登录':'注册并登录';}));
  document.querySelector('#authForm').addEventListener('submit',async(e)=>{e.preventDefault();const username=document.querySelector('#authUser').value.trim();const password=document.querySelector('#authPass').value;if(!username||!password)return toast('请输入用户名和密码');try{const res=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({username,password})});const data=await res.json();if(!res.ok)return toast(data.error||'操作失败');state.user=data.user;state.route='/chat';render();}catch(err){toast('网络错误，请重试');}});
}
app.addEventListener('click',event=>{const logout=event.target.closest('[data-action="logout"]');if(logout){event.preventDefault();doLogout();return;}const sidebarToggle=event.target.closest('[data-action="toggle-sidebar"]');if(sidebarToggle){event.preventDefault();if(isMobile()){setSidebar(!document.querySelector('.chat-shell').classList.contains('sidebar-open'));}else{document.querySelector('.chat-shell').classList.toggle('sidebar-collapsed');}return;}const scrim=event.target.closest('[data-action="close-sidebar"]');if(scrim){event.preventDefault();closeSidebar();return;}const prompt=event.target.closest('[data-prompt]');if(prompt){const input=document.querySelector('#prompt');input.value=prompt.dataset.prompt;input.focus();document.querySelector('#send').disabled=false;}const open=event.target.closest('[data-open-chat]');if(open){state.conversationId=open.dataset.openChat;navigate('/chat');}});render();
